Update patch set 8
Patch Set 8:

git push ssh://ThEMarD@review.lineageos.org:29418/LineageOS/android_device_leeco_x2 29762935827f23776e49c9820ff152651404c6e2:refs/for/lineage-15.1%ready
Counting objects: 17, done.
Delta compression using up to 6 threads.
Compressing objects: 100% (17/17), done.
Writing objects: 100% (17/17), 3.33 KiB | 0 bytes/s, done.
Total 17 (delta 12), reused 0 (delta 0)
remote: Resolving deltas: 100% (12/12)
remote: Processing changes: refs: 1, done    
remote: (W) No changes between prior commit 67eba38 and new commit a5ea4f7
remote: (I) 2976293: no files changed, was rebased
To ssh://ThEMarD@review.lineageos.org:29418/LineageOS/android_device_leeco_x2
 ! [remote rejected] 29762935827f23776e49c9820ff152651404c6e2 -> refs/for/lineage-15.1%ready (only change owner can modify Work-in-Progress)
error: failed to push some refs to 'ssh://ThEMarD@review.lineageos.org:29418/LineageOS/android_device_leeco_x2'

Patch-set: 8
Reviewer: Marc Bourgoin <18394@1ec6b3db-b2c1-4fa4-84a2-4c7efe89ba71>